// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm7Wk6Cut8tErIImQF0Wu9AXwUNWrB1Mg',
    appId: '1:397809957641:web:de9e8d05d3c884620e71d8',
    messagingSenderId: '397809957641',
    projectId: 'orderfoodapp-b6e54',
    authDomain: 'orderfoodapp-b6e54.firebaseapp.com',
    storageBucket: 'orderfoodapp-b6e54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKQ5srJsUjYe1Iv2hg657sPUo8qPm_Hio',
    appId: '1:397809957641:android:c9a1d1cefd3cd7d90e71d8',
    messagingSenderId: '397809957641',
    projectId: 'orderfoodapp-b6e54',
    storageBucket: 'orderfoodapp-b6e54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsJRFO7PBoCQ4U6LkMxyTpZxqdD7XKiyQ',
    appId: '1:397809957641:ios:c8273f67869738970e71d8',
    messagingSenderId: '397809957641',
    projectId: 'orderfoodapp-b6e54',
    storageBucket: 'orderfoodapp-b6e54.appspot.com',
    iosBundleId: 'com.example.oderfoodappFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsJRFO7PBoCQ4U6LkMxyTpZxqdD7XKiyQ',
    appId: '1:397809957641:ios:c8273f67869738970e71d8',
    messagingSenderId: '397809957641',
    projectId: 'orderfoodapp-b6e54',
    storageBucket: 'orderfoodapp-b6e54.appspot.com',
    iosBundleId: 'com.example.oderfoodappFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm7Wk6Cut8tErIImQF0Wu9AXwUNWrB1Mg',
    appId: '1:397809957641:web:f58225612eb7ba520e71d8',
    messagingSenderId: '397809957641',
    projectId: 'orderfoodapp-b6e54',
    authDomain: 'orderfoodapp-b6e54.firebaseapp.com',
    storageBucket: 'orderfoodapp-b6e54.appspot.com',
  );
}
